# Generated by Django 5.2.7 on 2025-10-21 19:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialvouch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income_document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_document_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='national_id_document',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_document_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_document_path),
        ),
        migrations.AlterField(
            model_name='socialvouch',
            name='max_cosign_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='socialvouch',
            name='trust_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')]),
        ),
    ]
