# Generated by Django 5.2.7 on 2025-10-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_socialvouch_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsdeposit',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Regular Deposit'), ('LOAN_DEPOSIT', 'Loan Deposit'), ('REPAYMENT_DEDUCTION', 'Repayment Deduction')], default='DEPOSIT', max_length=20),
        ),
    ]
